// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.model.quiz;

privileged aspect ChoiceBuilder_Roo_JavaBean {
    
    public Choice ChoiceBuilder.getChoice() {
        return this.choice;
    }
    
    public void ChoiceBuilder.setChoice(Choice choice) {
        this.choice = choice;
    }
    
}
