// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.web.form;

import com.chariot.games.quizzo.web.form.TeamSetupForm;
import java.io.Serializable;

privileged aspect TeamSetupForm_Roo_Serializable {
    
    declare parents: TeamSetupForm implements Serializable;
    
    private static final long TeamSetupForm.serialVersionUID = 1L;
    
}
