// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.db;

import com.chariot.games.quizzo.db.AnswerByChoiceRepository;
import org.springframework.stereotype.Repository;

privileged aspect AnswerByChoiceRepository_Roo_Jpa_Repository {
    
    declare @type: AnswerByChoiceRepository: @Repository;
    
}
