// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.model;

import com.chariot.games.quizzo.db.AnswerByChoiceRepository;
import com.chariot.games.quizzo.model.AnswerByChoiceDataOnDemand;
import com.chariot.games.quizzo.model.AnswerByChoiceIntegrationTest;
import com.chariot.games.quizzo.service.AnswerByChoiceService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AnswerByChoiceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AnswerByChoiceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AnswerByChoiceIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AnswerByChoiceIntegrationTest: @Transactional;
    
    @Autowired
    private AnswerByChoiceDataOnDemand AnswerByChoiceIntegrationTest.dod;
    
    @Autowired
    AnswerByChoiceService AnswerByChoiceIntegrationTest.answerByChoiceService;
    
    @Autowired
    AnswerByChoiceRepository AnswerByChoiceIntegrationTest.answerByChoiceRepository;
    
    @Test
    public void AnswerByChoiceIntegrationTest.testCountAllAnswerByChoices() {
        Assert.assertNotNull("Data on demand for 'AnswerByChoice' failed to initialize correctly", dod.getRandomAnswerByChoice());
        long count = answerByChoiceService.countAllAnswerByChoices();
        Assert.assertTrue("Counter for 'AnswerByChoice' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AnswerByChoiceIntegrationTest.testFindAnswerByChoice() {
        AnswerByChoice obj = dod.getRandomAnswerByChoice();
        Assert.assertNotNull("Data on demand for 'AnswerByChoice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AnswerByChoice' failed to provide an identifier", id);
        obj = answerByChoiceService.findAnswerByChoice(id);
        Assert.assertNotNull("Find method for 'AnswerByChoice' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AnswerByChoice' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AnswerByChoiceIntegrationTest.testFindAllAnswerByChoices() {
        Assert.assertNotNull("Data on demand for 'AnswerByChoice' failed to initialize correctly", dod.getRandomAnswerByChoice());
        long count = answerByChoiceService.countAllAnswerByChoices();
        Assert.assertTrue("Too expensive to perform a find all test for 'AnswerByChoice', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AnswerByChoice> result = answerByChoiceService.findAllAnswerByChoices();
        Assert.assertNotNull("Find all method for 'AnswerByChoice' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AnswerByChoice' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AnswerByChoiceIntegrationTest.testFindAnswerByChoiceEntries() {
        Assert.assertNotNull("Data on demand for 'AnswerByChoice' failed to initialize correctly", dod.getRandomAnswerByChoice());
        long count = answerByChoiceService.countAllAnswerByChoices();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AnswerByChoice> result = answerByChoiceService.findAnswerByChoiceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AnswerByChoice' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AnswerByChoice' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AnswerByChoiceIntegrationTest.testFlush() {
        AnswerByChoice obj = dod.getRandomAnswerByChoice();
        Assert.assertNotNull("Data on demand for 'AnswerByChoice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AnswerByChoice' failed to provide an identifier", id);
        obj = answerByChoiceService.findAnswerByChoice(id);
        Assert.assertNotNull("Find method for 'AnswerByChoice' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAnswerByChoice(obj);
        Integer currentVersion = obj.getVersion();
        answerByChoiceRepository.flush();
        Assert.assertTrue("Version for 'AnswerByChoice' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AnswerByChoiceIntegrationTest.testUpdateAnswerByChoiceUpdate() {
        AnswerByChoice obj = dod.getRandomAnswerByChoice();
        Assert.assertNotNull("Data on demand for 'AnswerByChoice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AnswerByChoice' failed to provide an identifier", id);
        obj = answerByChoiceService.findAnswerByChoice(id);
        boolean modified =  dod.modifyAnswerByChoice(obj);
        Integer currentVersion = obj.getVersion();
        AnswerByChoice merged = (AnswerByChoice)answerByChoiceService.updateAnswerByChoice(obj);
        answerByChoiceRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AnswerByChoice' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AnswerByChoiceIntegrationTest.testSaveAnswerByChoice() {
        Assert.assertNotNull("Data on demand for 'AnswerByChoice' failed to initialize correctly", dod.getRandomAnswerByChoice());
        AnswerByChoice obj = dod.getNewTransientAnswerByChoice(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AnswerByChoice' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AnswerByChoice' identifier to be null", obj.getId());
        answerByChoiceService.saveAnswerByChoice(obj);
        answerByChoiceRepository.flush();
        Assert.assertNotNull("Expected 'AnswerByChoice' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AnswerByChoiceIntegrationTest.testDeleteAnswerByChoice() {
        AnswerByChoice obj = dod.getRandomAnswerByChoice();
        Assert.assertNotNull("Data on demand for 'AnswerByChoice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AnswerByChoice' failed to provide an identifier", id);
        obj = answerByChoiceService.findAnswerByChoice(id);
        answerByChoiceService.deleteAnswerByChoice(obj);
        answerByChoiceRepository.flush();
        Assert.assertNull("Failed to remove 'AnswerByChoice' with identifier '" + id + "'", answerByChoiceService.findAnswerByChoice(id));
    }
    
}
