// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.model;

import com.chariot.games.quizzo.db.AnswerRepository;
import com.chariot.games.quizzo.model.Answer;
import com.chariot.games.quizzo.model.AnswerDataOnDemand;
import com.chariot.games.quizzo.model.Question;
import com.chariot.games.quizzo.model.QuestionDataOnDemand;
import com.chariot.games.quizzo.service.AnswerService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AnswerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AnswerDataOnDemand: @Component;
    
    private Random AnswerDataOnDemand.rnd = new SecureRandom();
    
    private List<Answer> AnswerDataOnDemand.data;
    
    @Autowired
    private QuestionDataOnDemand AnswerDataOnDemand.questionDataOnDemand;
    
    @Autowired
    AnswerService AnswerDataOnDemand.answerService;
    
    @Autowired
    AnswerRepository AnswerDataOnDemand.answerRepository;
    
    public Answer AnswerDataOnDemand.getNewTransientAnswer(int index) {
        Answer obj = new Answer();
        setAnswerText(obj, index);
        setIsCorrectAnswer(obj, index);
        setQuestion(obj, index);
        setQuestionOrder(obj, index);
        return obj;
    }
    
    public void AnswerDataOnDemand.setAnswerText(Answer obj, int index) {
        String answerText = "answerText_" + index;
        obj.setAnswerText(answerText);
    }
    
    public void AnswerDataOnDemand.setIsCorrectAnswer(Answer obj, int index) {
        Boolean isCorrectAnswer = Boolean.TRUE;
        obj.setIsCorrectAnswer(isCorrectAnswer);
    }
    
    public void AnswerDataOnDemand.setQuestion(Answer obj, int index) {
        Question question = questionDataOnDemand.getRandomQuestion();
        obj.setQuestion(question);
    }
    
    public void AnswerDataOnDemand.setQuestionOrder(Answer obj, int index) {
        Integer questionOrder = new Integer(index);
        obj.setQuestionOrder(questionOrder);
    }
    
    public Answer AnswerDataOnDemand.getSpecificAnswer(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Answer obj = data.get(index);
        Long id = obj.getId();
        return answerService.findAnswer(id);
    }
    
    public Answer AnswerDataOnDemand.getRandomAnswer() {
        init();
        Answer obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return answerService.findAnswer(id);
    }
    
    public boolean AnswerDataOnDemand.modifyAnswer(Answer obj) {
        return false;
    }
    
    public void AnswerDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = answerService.findAnswerEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Answer' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Answer>();
        for (int i = 0; i < 10; i++) {
            Answer obj = getNewTransientAnswer(i);
            try {
                answerService.saveAnswer(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            answerRepository.flush();
            data.add(obj);
        }
    }
    
}
