// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.model;

import com.chariot.games.quizzo.db.FillInTheBlankAnswerRepository;
import com.chariot.games.quizzo.model.FillInTheBlankAnswer;
import com.chariot.games.quizzo.model.FillInTheBlankAnswerDataOnDemand;
import com.chariot.games.quizzo.model.Question;
import com.chariot.games.quizzo.model.Team;
import com.chariot.games.quizzo.service.FillInTheBlankAnswerService;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FillInTheBlankAnswerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FillInTheBlankAnswerDataOnDemand: @Component;
    
    private Random FillInTheBlankAnswerDataOnDemand.rnd = new SecureRandom();
    
    private List<FillInTheBlankAnswer> FillInTheBlankAnswerDataOnDemand.data;
    
    @Autowired
    FillInTheBlankAnswerService FillInTheBlankAnswerDataOnDemand.fillInTheBlankAnswerService;
    
    @Autowired
    FillInTheBlankAnswerRepository FillInTheBlankAnswerDataOnDemand.fillInTheBlankAnswerRepository;
    
    public FillInTheBlankAnswer FillInTheBlankAnswerDataOnDemand.getNewTransientFillInTheBlankAnswer(int index) {
        FillInTheBlankAnswer obj = new FillInTheBlankAnswer();
        setBonusPoints(obj, index);
        setQuestion(obj, index);
        setTeam(obj, index);
        return obj;
    }
    
    public void FillInTheBlankAnswerDataOnDemand.setBonusPoints(FillInTheBlankAnswer obj, int index) {
        BigDecimal bonusPoints = BigDecimal.valueOf(index);
        if (bonusPoints.compareTo(new BigDecimal("-100.0")) == -1 || bonusPoints.compareTo(new BigDecimal("100.0")) == 1) {
            bonusPoints = new BigDecimal("100.0");
        }
        obj.setBonusPoints(bonusPoints);
    }
    
    public void FillInTheBlankAnswerDataOnDemand.setQuestion(FillInTheBlankAnswer obj, int index) {
        Question question = null;
        obj.setQuestion(question);
    }
    
    public void FillInTheBlankAnswerDataOnDemand.setTeam(FillInTheBlankAnswer obj, int index) {
        Team team = null;
        obj.setTeam(team);
    }
    
    public FillInTheBlankAnswer FillInTheBlankAnswerDataOnDemand.getSpecificFillInTheBlankAnswer(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        FillInTheBlankAnswer obj = data.get(index);
        Long id = obj.getId();
        return fillInTheBlankAnswerService.findFillInTheBlankAnswer(id);
    }
    
    public FillInTheBlankAnswer FillInTheBlankAnswerDataOnDemand.getRandomFillInTheBlankAnswer() {
        init();
        FillInTheBlankAnswer obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return fillInTheBlankAnswerService.findFillInTheBlankAnswer(id);
    }
    
    public boolean FillInTheBlankAnswerDataOnDemand.modifyFillInTheBlankAnswer(FillInTheBlankAnswer obj) {
        return false;
    }
    
    public void FillInTheBlankAnswerDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = fillInTheBlankAnswerService.findFillInTheBlankAnswerEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'FillInTheBlankAnswer' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<FillInTheBlankAnswer>();
        for (int i = 0; i < 10; i++) {
            FillInTheBlankAnswer obj = getNewTransientFillInTheBlankAnswer(i);
            try {
                fillInTheBlankAnswerService.saveFillInTheBlankAnswer(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            fillInTheBlankAnswerRepository.flush();
            data.add(obj);
        }
    }
    
}
