// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.model;

import com.chariot.games.quizzo.model.MultipleChoiceQuestionDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MultipleChoiceQuestionDataOnDemand_Roo_Configurable {
    
    declare @type: MultipleChoiceQuestionDataOnDemand: @Configurable;
    
}
