// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.model;

import com.chariot.games.quizzo.db.QuestionRepository;
import com.chariot.games.quizzo.model.QuestionDataOnDemand;
import com.chariot.games.quizzo.model.QuestionIntegrationTest;
import com.chariot.games.quizzo.service.QuestionService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect QuestionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: QuestionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: QuestionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: QuestionIntegrationTest: @Transactional;
    
    @Autowired
    private QuestionDataOnDemand QuestionIntegrationTest.dod;
    
    @Autowired
    QuestionService QuestionIntegrationTest.questionService;
    
    @Autowired
    QuestionRepository QuestionIntegrationTest.questionRepository;
    
    @Test
    public void QuestionIntegrationTest.testCountAllQuestions() {
        Assert.assertNotNull("Data on demand for 'Question' failed to initialize correctly", dod.getRandomQuestion());
        long count = questionService.countAllQuestions();
        Assert.assertTrue("Counter for 'Question' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void QuestionIntegrationTest.testFindQuestion() {
        Question obj = dod.getRandomQuestion();
        Assert.assertNotNull("Data on demand for 'Question' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Question' failed to provide an identifier", id);
        obj = questionService.findQuestion(id);
        Assert.assertNotNull("Find method for 'Question' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Question' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void QuestionIntegrationTest.testFindAllQuestions() {
        Assert.assertNotNull("Data on demand for 'Question' failed to initialize correctly", dod.getRandomQuestion());
        long count = questionService.countAllQuestions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Question', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Question> result = questionService.findAllQuestions();
        Assert.assertNotNull("Find all method for 'Question' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Question' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void QuestionIntegrationTest.testFindQuestionEntries() {
        Assert.assertNotNull("Data on demand for 'Question' failed to initialize correctly", dod.getRandomQuestion());
        long count = questionService.countAllQuestions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Question> result = questionService.findQuestionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Question' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Question' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void QuestionIntegrationTest.testFlush() {
        Question obj = dod.getRandomQuestion();
        Assert.assertNotNull("Data on demand for 'Question' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Question' failed to provide an identifier", id);
        obj = questionService.findQuestion(id);
        Assert.assertNotNull("Find method for 'Question' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyQuestion(obj);
        Integer currentVersion = obj.getVersion();
        questionRepository.flush();
        Assert.assertTrue("Version for 'Question' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionIntegrationTest.testUpdateQuestionUpdate() {
        Question obj = dod.getRandomQuestion();
        Assert.assertNotNull("Data on demand for 'Question' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Question' failed to provide an identifier", id);
        obj = questionService.findQuestion(id);
        boolean modified =  dod.modifyQuestion(obj);
        Integer currentVersion = obj.getVersion();
        Question merged = questionService.updateQuestion(obj);
        questionRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Question' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionIntegrationTest.testSaveQuestion() {
        Assert.assertNotNull("Data on demand for 'Question' failed to initialize correctly", dod.getRandomQuestion());
        Question obj = dod.getNewTransientQuestion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Question' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Question' identifier to be null", obj.getId());
        questionService.saveQuestion(obj);
        questionRepository.flush();
        Assert.assertNotNull("Expected 'Question' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void QuestionIntegrationTest.testDeleteQuestion() {
        Question obj = dod.getRandomQuestion();
        Assert.assertNotNull("Data on demand for 'Question' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Question' failed to provide an identifier", id);
        obj = questionService.findQuestion(id);
        questionService.deleteQuestion(obj);
        questionRepository.flush();
        Assert.assertNull("Failed to remove 'Question' with identifier '" + id + "'", questionService.findQuestion(id));
    }
    
}
