// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.model;

import com.chariot.games.quizzo.model.QuizRun;
import com.chariot.games.quizzo.model.QuizRunDataOnDemand;
import com.chariot.games.quizzo.model.QuizRunIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect QuizRunIntegrationTest_Roo_IntegrationTest {
    
    declare @type: QuizRunIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: QuizRunIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: QuizRunIntegrationTest: @Transactional;
    
    @Autowired
    private QuizRunDataOnDemand QuizRunIntegrationTest.dod;
    
    @Test
    public void QuizRunIntegrationTest.testCountQuizRuns() {
        Assert.assertNotNull("Data on demand for 'QuizRun' failed to initialize correctly", dod.getRandomQuizRun());
        long count = QuizRun.countQuizRuns();
        Assert.assertTrue("Counter for 'QuizRun' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void QuizRunIntegrationTest.testFindQuizRun() {
        QuizRun obj = dod.getRandomQuizRun();
        Assert.assertNotNull("Data on demand for 'QuizRun' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuizRun' failed to provide an identifier", id);
        obj = QuizRun.findQuizRun(id);
        Assert.assertNotNull("Find method for 'QuizRun' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'QuizRun' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void QuizRunIntegrationTest.testFindAllQuizRuns() {
        Assert.assertNotNull("Data on demand for 'QuizRun' failed to initialize correctly", dod.getRandomQuizRun());
        long count = QuizRun.countQuizRuns();
        Assert.assertTrue("Too expensive to perform a find all test for 'QuizRun', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<QuizRun> result = QuizRun.findAllQuizRuns();
        Assert.assertNotNull("Find all method for 'QuizRun' illegally returned null", result);
        Assert.assertTrue("Find all method for 'QuizRun' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void QuizRunIntegrationTest.testFindQuizRunEntries() {
        Assert.assertNotNull("Data on demand for 'QuizRun' failed to initialize correctly", dod.getRandomQuizRun());
        long count = QuizRun.countQuizRuns();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<QuizRun> result = QuizRun.findQuizRunEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'QuizRun' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'QuizRun' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void QuizRunIntegrationTest.testFlush() {
        QuizRun obj = dod.getRandomQuizRun();
        Assert.assertNotNull("Data on demand for 'QuizRun' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuizRun' failed to provide an identifier", id);
        obj = QuizRun.findQuizRun(id);
        Assert.assertNotNull("Find method for 'QuizRun' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyQuizRun(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'QuizRun' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuizRunIntegrationTest.testMergeUpdate() {
        QuizRun obj = dod.getRandomQuizRun();
        Assert.assertNotNull("Data on demand for 'QuizRun' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuizRun' failed to provide an identifier", id);
        obj = QuizRun.findQuizRun(id);
        boolean modified =  dod.modifyQuizRun(obj);
        Integer currentVersion = obj.getVersion();
        QuizRun merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'QuizRun' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuizRunIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'QuizRun' failed to initialize correctly", dod.getRandomQuizRun());
        QuizRun obj = dod.getNewTransientQuizRun(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'QuizRun' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'QuizRun' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'QuizRun' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void QuizRunIntegrationTest.testRemove() {
        QuizRun obj = dod.getRandomQuizRun();
        Assert.assertNotNull("Data on demand for 'QuizRun' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuizRun' failed to provide an identifier", id);
        obj = QuizRun.findQuizRun(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'QuizRun' with identifier '" + id + "'", QuizRun.findQuizRun(id));
    }
    
}
