// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.model;

import com.chariot.games.quizzo.model.QuizRunIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect QuizRunIntegrationTest_Roo_Configurable {
    
    declare @type: QuizRunIntegrationTest: @Configurable;
    
}
