// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.web.flow;

import com.chariot.games.quizzo.web.flow.VotingForm;
import java.io.Serializable;

privileged aspect VotingForm_Roo_Serializable {
    
    declare parents: VotingForm implements Serializable;
    
    private static final long VotingForm.serialVersionUID = 1L;
    
}
