// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.model;

import com.chariot.games.quizzo.model.MultipleChoiceQuestion;
import javax.persistence.Entity;

privileged aspect MultipleChoiceQuestion_Roo_Jpa_Entity {
    
    declare @type: MultipleChoiceQuestion: @Entity;
    
}
