// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.model;

import com.chariot.games.quizzo.model.TeamMember;

privileged aspect TeamMember_Roo_JavaBean {
    
    public String TeamMember.getName() {
        return this.name;
    }
    
    public void TeamMember.setName(String name) {
        this.name = name;
    }
    
}
