// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.model;

import com.chariot.games.quizzo.model.TeamMember;
import java.io.Serializable;

privileged aspect TeamMember_Roo_Serializable {
    
    declare parents: TeamMember implements Serializable;
    
    private static final long TeamMember.serialVersionUID = 1L;
    
}
