// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.model;

import com.chariot.games.quizzo.model.Vote;

privileged aspect Vote_Roo_JavaBean {
    
    public boolean Vote.isVote() {
        return this.vote;
    }
    
    public void Vote.setVote(boolean vote) {
        this.vote = vote;
    }
    
}
