// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.games.quizzo.web.admin;

import com.chariot.games.quizzo.web.admin.QuizSelectionForm;

privileged aspect QuizSelectionForm_Roo_JavaBean {
    
    public Long QuizSelectionForm.getId() {
        return this.id;
    }
    
    public void QuizSelectionForm.setId(Long id) {
        this.id = id;
    }
    
}
